// Code generated by go-swagger; DO NOT EDIT.

// Package restapi San Francisco Food Trucks Server
//
//  API description in Markdown.
//  Schemes:
//    https
//  Host: api.example.com
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
