// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetFoodtrucksAndLocationLocationParams creates a new GetFoodtrucksAndLocationLocationParams object
//
// There are no default values defined in the spec.
func NewGetFoodtrucksAndLocationLocationParams() GetFoodtrucksAndLocationLocationParams {

	return GetFoodtrucksAndLocationLocationParams{}
}

// GetFoodtrucksAndLocationLocationParams contains all the bound params for the get foodtrucks and location location operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetFoodtrucksAndLocationLocation
type GetFoodtrucksAndLocationLocationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the user to return.
	  Required: true
	  Minimum: 1
	  In: path
	*/
	Location int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFoodtrucksAndLocationLocationParams() beforehand.
func (o *GetFoodtrucksAndLocationLocationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rLocation, rhkLocation, _ := route.Params.GetOK("location")
	if err := o.bindLocation(rLocation, rhkLocation, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLocation binds and validates parameter Location from path.
func (o *GetFoodtrucksAndLocationLocationParams) bindLocation(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("location", "path", "int64", raw)
	}
	o.Location = value

	if err := o.validateLocation(formats); err != nil {
		return err
	}

	return nil
}

// validateLocation carries on validations for parameter Location
func (o *GetFoodtrucksAndLocationLocationParams) validateLocation(formats strfmt.Registry) error {

	if err := validate.MinimumInt("location", "path", o.Location, 1, false); err != nil {
		return err
	}

	return nil
}
