swagger: "2.0"
info:
  title: San Francisco Food Trucks Server
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /foodtrucks&location={location}:
    get:
      summary: Returns a list of food Trucks.
      description: Optional extended description in Markdown.
      parameters:
        - in: path
          name: location
          required: true
          type: integer
          minimum: 1
          description: The ID of the user to return.
      produces:
        - application/json
      responses:
        200:
          description: OK
